english = {
'primer': 'Before you start:',
'rule1': 'Put the armor on that you will optimize with',
'rule2': 'Put all your talismen in your inventory or talisman bag',
'rule3': 'Enable your skyblock API settings [skyblock menu > settings > api settings]',
'rule4': '',
'welcome': '',
'username?': '',
'unameaccept': '',
'neverplayedsb': '',
'invaliduname': '',
'profile?': '',
'sortbydate': '',
'apidisabled': '',
'reenable': '',
'thisappearsif': '',
'chooselisted': '',
'unnecessary': '',
'noweapon': 'You are not carrying any weapons!\nPlace one in your inventory and try again',
'weapon?': 'Which weapon do you want to use?',
'usenameornumber': 'Enter the weapon name or the weapon number',
'profileaccepted': 'Profile accepted!',
'correctequip?': 'Is this the correct equipment? [YES/NO]',
'ansy/n': 'Please answer with YES or NO',
'potion?': 'Do you use {potion_name} pots with this build? [YES/NO]',
'potionstats': 'Potion stats for {self.user}: {self.potion_stats}',
'potionlvl?': 'Which level of {damaging_potions[self.potion_id]["name"]} potions do you use?',
'enternumb': 'Invalid response! Enter a number',
'critgoal?': 'You indicated that you want don\'t want to use crit pots\nDo you want to have 80 crit chance anyway? [YES/NO]',
'overflux': 'I detected an overflux orb. Should I include that in the calcuations? [YES/NO]',
'manaflux': 'I detected a mana flux orb. Should I include that in the calcuations? [YES/NO]',
'tuba': 'I detected a weird tuba. Should I include that in the calcuations? [YES/NO]',
'target?': 'Which mob will you target with this setup?',
'pickactivities': 'Invalid response! Pick one of the activities',
'enchantmentmodifier': 'Enchantment modifier for {self.user}: {self.enchantment_modifier}',
'algstarted': 'Please wait. Your results will be sent shortly...',
'finished': 'Calculations complete!',
'disclaimer': '''Damage multipliers from weapons such as
scorpion foil or reaper falichion are not included.
Talisman results should still be correct.''',
'shoulddeal': '',
'withoutcrit': ''
}

spainish = {
'primer': '',
'rule1': '',
'rule2': '',
'rule3': '',
'rule4': '',
'welcome': '',
'username?': '',
'unameaccept': '',
'neverplayedsb': '',
'invaliduname': '',
'profile?': '',
'sortbydate': '',
'apidisabled': '',
'reenable': '',
'thisappearsif': '',
'chooselisted': '',
'unnecessary': '',
'noweapon': '',
'getaweapon': '',
'weapon?': '',
'enterrealweapon': '',
'profileaccepted': '',
'correctequip?': '',
'ansy/n': '',
'potion?': '',
'potionstats': '',
'potionlvl?': '',
'enternumb': '',
'critgoal?': '',
'overflux': '',
'manaflux': '',
'tuba': '',
'target?': '',
'pickactivities': '',
'enchantmentmodifier': '',
'algstarted': '',
'finished': '',
'disclaimer': '',
'shoulddeal': '',
'withoutcrit': ''
}